<a href="https://colab.research.google.com/github/pratyushprasad2323/tensors/blob/main/A2_tensors_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BASICS OF TENSOR FLOW

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# making a constant
a=tf.constant(4,dtype='float32')
print(a)

tf.Tensor(4.0, shape=(), dtype=float32)


In [3]:
b=tf.constant([1.0,2,3,4])
print(b)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [4]:
c=tf.constant([[1.0,2,3,4],[5,6,7,8]])
print(c)

tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)


In [5]:
d=tf.constant(np.arange(27).reshape([3,3,3]))
print(d)

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]], shape=(3, 3, 3), dtype=int64)


In [6]:
# converting tensor matrice to numpy array
print(np.array(d))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
d.numpy()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
# tensor flow can contain other datatypes as well such as complex numbers and strings
# remember while initializing any tensor matrix, it has to be rectangular

# basic operations on tensor flow

a=tf.Variable([[1,2,3],[4,5,6]],dtype='float32')
b=tf.Variable([[2,3,4],[5,6,7]],dtype='float32')

In [9]:
print(tf.add(a,b))

tf.Tensor(
[[ 3.  5.  7.]
 [ 9. 11. 13.]], shape=(2, 3), dtype=float32)


In [10]:
print(tf.multiply(a,b))

tf.Tensor(
[[ 2.  6. 12.]
 [20. 30. 42.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.matmul(a,tf.transpose(a)))

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [12]:
print(a+b)

tf.Tensor(
[[ 3.  5.  7.]
 [ 9. 11. 13.]], shape=(2, 3), dtype=float32)


In [13]:
print(a*b)

tf.Tensor(
[[ 2.  6. 12.]
 [20. 30. 42.]], shape=(2, 3), dtype=float32)


In [14]:
print(a@tf.transpose(a))

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [15]:
a=tf.Variable([[1,2],[3,4]],dtype='float32')
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [16]:
print(tf.reduce_max(a))
print(tf.reduce_min(a))

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [17]:
print(tf.math.argmax(a))

tf.Tensor([1 1], shape=(2,), dtype=int64)


In [18]:
# logistic regression logic
print(tf.nn.softmax(a))

tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.26894143 0.7310586 ]], shape=(2, 2), dtype=float32)


In [19]:
a=tf.Variable([[1,2,10],[4,3,2],[3,5,4]],dtype='float32')
print(tf.nn.softmax(a))

tf.Tensor(
[[1.2335321e-04 3.3530878e-04 9.9954140e-01]
 [6.6524094e-01 2.4472848e-01 9.0030573e-02]
 [9.0030566e-02 6.6524088e-01 2.4472845e-01]], shape=(3, 3), dtype=float32)


## ABOUT SHAPES
1. shape - the length of each axis
2. rank - number of tensor axis, scalar has 0
3. axis - dimension of the tensor
4. size - total number of items in the tensor

In [20]:
a_rank_4=tf.Variable(np.arange(100).reshape([2,5,2,5]))
print(a_rank_4)

<tf.Variable 'Variable:0' shape=(2, 5, 2, 5) dtype=int64, numpy=
array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89]],

        [[90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])>


In [21]:
print('data type of every element : ',a_rank_4.dtype)   # datatype
print('number of axis : ',tf.rank(a_rank_4))            # rank
print('shape of tensor : ',a_rank_4.shape)              # shape
print('matrix as numpy array \n', a_rank_4.numpy())     # tensor to numpy

data type of every element :  <dtype: 'int64'>
number of axis :  tf.Tensor(4, shape=(), dtype=int32)
shape of tensor :  (2, 5, 2, 5)
matrix as numpy array 
 [[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]

  [[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]

  [[40 41 42 43 44]
   [45 46 47 48 49]]]


 [[[50 51 52 53 54]
   [55 56 57 58 59]]

  [[60 61 62 63 64]
   [65 66 67 68 69]]

  [[70 71 72 73 74]
   [75 76 77 78 79]]

  [[80 81 82 83 84]
   [85 86 87 88 89]]

  [[90 91 92 93 94]
   [95 96 97 98 99]]]]


In [22]:
# slicing
print(a_rank_4[1])
print(a_rank_4[:,1])
print(a_rank_4[:,:,1])
print(a_rank_4[:,:,:,1])

tf.Tensor(
[[[50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]

 [[70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]]

 [[90 91 92 93 94]
  [95 96 97 98 99]]], shape=(5, 2, 5), dtype=int64)
tf.Tensor(
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]], shape=(2, 2, 5), dtype=int64)
tf.Tensor(
[[[ 5  6  7  8  9]
  [15 16 17 18 19]
  [25 26 27 28 29]
  [35 36 37 38 39]
  [45 46 47 48 49]]

 [[55 56 57 58 59]
  [65 66 67 68 69]
  [75 76 77 78 79]
  [85 86 87 88 89]
  [95 96 97 98 99]]], shape=(2, 5, 5), dtype=int64)
tf.Tensor(
[[[ 1  6]
  [11 16]
  [21 26]
  [31 36]
  [41 46]]

 [[51 56]
  [61 66]
  [71 76]
  [81 86]
  [91 96]]], shape=(2, 5, 2), dtype=int64)


In [23]:
# manipulating shapes
x=tf.constant([[1],[2],[3]])
print(x)
print(x.shape)
print(tf.reshape(x,[1,3]))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


## MORE ON DTYPES 

In [24]:
# changing the datatype of the variable
a=tf.Variable([1.414,2.731,3.141],dtype='float64')      
b=tf.Variable([1.000,1.414,1.731],dtype='float16')
c=tf.Variable([1,3,5],dtype=tf.uint8)
print(a,'\n',b,'\n',c)

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([1.414, 2.731, 3.141])> 
 <tf.Variable 'Variable:0' shape=(3,) dtype=float16, numpy=array([1.   , 1.414, 1.731], dtype=float16)> 
 <tf.Variable 'Variable:0' shape=(3,) dtype=uint8, numpy=array([1, 3, 5], dtype=uint8)>


## BROADCASTING

under certain conditions, smaller tensors are stretched automatically to fit larger tensor when running combined operation on them.

In [25]:
x=tf.Variable([[1,2,3],[2,3,4],[3,4,5]],dtype='float32')
y=tf.Variable(3,dtype='float32')
print(tf.multiply(x,y))
print(tf.add(x,y))
z=tf.Variable(np.array([1,2,3]).reshape(3,-1))
print(z)

tf.Tensor(
[[ 3.  6.  9.]
 [ 6.  9. 12.]
 [ 9. 12. 15.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]], shape=(3, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int64, numpy=
array([[1],
       [2],
       [3]])>


In [26]:
x_stretch=tf.constant([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
y_stretch=tf.constant([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(x_stretch*y_stretch)

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


## RAGGED TENSORS

they are tensors with variable number of elements in its axis.

In [27]:
ragged_list=[[0,1,2,3],[4,5],[6,7,8],[9]]
try:
  tensor=tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [28]:
# initializing a ragged tensor
a=tf.ragged.constant(ragged_list)
print(a)
print(a.shape)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


STRING TENSORS

In [29]:
# operations on string
a=tf.constant('pratyush prasad')
print(a)
a=tf.constant(['pratyush','gupta','prasad'])
print(a)
a=tf.constant(['good morning','good afternoon','good evening','good night'])
print(tf.strings.split(a,sep=" "))

tf.Tensor(b'pratyush prasad', shape=(), dtype=string)
tf.Tensor([b'pratyush' b'gupta' b'prasad'], shape=(3,), dtype=string)
<tf.RaggedTensor [[b'good', b'morning'],
 [b'good', b'afternoon'],
 [b'good', b'evening'],
 [b'good', b'night']]>


In [30]:
a=tf.strings.bytes_split(tf.constant('BHOOT BABA 2323 .'))
a=tf.io.decode_raw(tf.constant('BHOOT BABA 2323 .'),tf.uint8)
print("Byte strings:",a)
print("Bytes:",b)

Byte strings: tf.Tensor([66 72 79 79 84 32 66 65 66 65 32 50 51 50 51 32 46], shape=(17,), dtype=uint8)
Bytes: <tf.Variable 'Variable:0' shape=(3,) dtype=float16, numpy=array([1.   , 1.414, 1.731], dtype=float16)>


In [31]:
# sparse tensor
sparse_tensor=tf.sparse.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3, 4])
print(sparse_tensor)
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
