<a href="https://colab.research.google.com/github/pratyushprasad2323/tensors/blob/main/A3_tensors_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCTION TO VARIABLES

a variable of tensor flow can be manipulated through programmes easily. to create a variable we have to type tf.Variable. 

Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running operations on it. Specific ops allow you to read and modify the values of this tensor.

## CREATING A VARIABLE

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a=tf.constant([[1,2,3],[2,3,4]])
b=tf.Variable(a)
c=tf.Variable([True,False,True])
d=tf.Variable([1+2j,3+4j])

In [3]:
print(b.shape)
print(b.dtype)
print(b.numpy())

(2, 3)
<dtype: 'int32'>
[[1 2 3]
 [2 3 4]]


In [4]:
print(b)
print(tf.convert_to_tensor(b))
print(tf.math.argmax(b))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>
tf.Tensor(
[[1 2 3]
 [2 3 4]], shape=(2, 3), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)


In [5]:
# checking if the assign keyword work if the size changes
a=tf.Variable([2.0,3.0])
print(a)
a.assign([1,2]) 
print(a)
try:
  a.assign([1.0, 2.0, 3.0])
  print(a)
except Exception as e:
  print(f"{type(e).__name__}: {e}")
  print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [6]:
# basic operation of addition and subtraction
a=tf.Variable([1,2,3])
b=tf.Variable(a)

a.assign([2,3,4])

print(a.numpy())
print(b.numpy())

print(a.assign_add([5,6,8]).numpy())
print(a.assign_sub([4,5,9]).numpy())

[2 3 4]
[1 2 3]
[ 7  9 12]
[3 4 3]


## LIFECYCLE, NAMING AND WATCHIN

In python based TF, tf.Variable instance have the same lifecycle as other python objects. variable names are preserved when saving and loading models. by default variables in models will acquire unique variable names automatically

In [7]:
a=tf.Variable([2,5,8,3],dtype='float32')
b=tf.Variable(a,name='var')
c=tf.Variable(a+1,name='var')
print(b==c)

tf.Tensor([False False False False], shape=(4,), dtype=bool)


## PLACING VARIABLES AND TENSORS

For better performance, TF will attempt to place tensors and variables on the fastest device compatible with its dtype. this means most variables are placed on a GPU.

In [8]:
# using only CPU for computation
with tf.device('CPU:0'):
  a=tf.Variable([[1.0,2.0,3.0],[4.0,5.0,6.0]])
  b=tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
  c=tf.matmul(a,b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [9]:
# using CPU and GPU for computation
with tf.device('CPU:0'):
  a=tf.Variable([[1.0,2.0,3.0],[4.0,5.0,6.0]])
  b=tf.Variable([[1.0,2.0,3.0]])
with tf.device('GPU:0'):
  k=a*b

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
